"""Regenerate app/lib/imageSizes.ts from the files in public/images.
Run after adding or replacing images:  python scripts/gen-image-sizes.py
Intrinsic width/height on <img> is what lets the browser reserve space before
the image loads, which is what keeps CLS down."""
import glob, os
from PIL import Image

rows = []
for f in sorted(glob.glob("public/images/*")):
    try:
        with Image.open(f) as im:
            w, h = im.size
    except Exception:
        continue
    rows.append(f'  "/images/{os.path.basename(f)}": [{w}, {h}],')

out = (
    "// GENERATED by scripts/gen-image-sizes.py - do not edit by hand.\n"
    "// Intrinsic sizes so <img> can reserve layout space and avoid CLS.\n"
    "export const IMAGE_SIZES: Record<string, [number, number]> = {\n"
    + "\n".join(rows)
    + "\n};\n\n"
    "/** Spread onto an <img> to give it intrinsic dimensions when known. */\n"
    "export function dims(src?: string) {\n"
    "  const s = src ? IMAGE_SIZES[src.split('?')[0]] : undefined;\n"
    "  return s ? { width: s[0], height: s[1] } : {};\n"
    "}\n"
)
os.makedirs("app/lib", exist_ok=True)
open("app/lib/imageSizes.ts", "w", encoding="utf-8").write(out)
print(f"wrote app/lib/imageSizes.ts with {len(rows)} images")
