"""Regenerate app/lib/contentDates.ts from git history.

Google uses <lastmod> for crawl scheduling but ignores <changefreq> and
<priority>. It also discounts lastmod entirely if it looks unreliable, so these
dates are taken from the last commit that actually touched the files behind
each route rather than being stamped with the build time.

Run after content changes:  python scripts/gen-content-dates.py
"""
import json, os, re, subprocess

def last_commit(paths):
    best = ""
    for p in paths:
        if not os.path.exists(p):
            continue
        try:
            out = subprocess.run(
                ["git", "log", "-1", "--format=%cI", "--", p],
                capture_output=True, text=True, check=True).stdout.strip()
        except Exception:
            out = ""
        if out > best:
            best = out
    return best[:10]

def slugs(path, key="slug"):
    src = open(path, encoding="utf-8").read()
    return re.findall(key + r':\s*"([^"]+)"', src)

TPL = "app/services/[slug]/page.tsx"
AREA_TPL = "app/areas/[slug]/page.tsx"
GUIDE_TPL = "app/(guides)/GuideArticle.tsx"

routes = {}
for s in slugs("app/services/serviceData.ts"):
    routes[f"/services/{s}"] = last_commit(["app/services/serviceData.ts", TPL])
for a in slugs("app/areas/areaData.ts"):
    routes[f"/areas/{a}"] = last_commit(["app/areas/areaData.ts", AREA_TPL])
for g in slugs("app/(guides)/guidesData.ts"):
    routes[f"/{g}"] = last_commit(["app/(guides)/guidesData.ts", GUIDE_TPL])

STATIC = {
    "/": ["public/premium.html"],
    "/services": ["app/services/page.tsx", "app/services/serviceData.ts"],
    "/areas": ["app/areas/page.tsx", "app/areas/areaData.ts"],
    "/book": ["app/book/page.tsx"],
    "/courses": ["app/courses/page.tsx"],
    "/blog": ["app/blog/page.tsx", "app/blog/posts.ts"],
    "/gallery": ["app/gallery/Gallery.tsx", "app/gallery/galleryData.ts"],
    "/faq": ["app/faq/page.tsx"],
    "/contact": ["app/(legal)/contact/page.tsx"],
    "/about": ["app/(legal)/about/page.tsx"],
    "/privacy-policy": ["app/(legal)/privacy-policy/page.tsx"],
    "/terms": ["app/(legal)/terms/page.tsx"],
}
for r, files in STATIC.items():
    routes[r] = last_commit(files)

routes = {k: v for k, v in routes.items() if v}
body = "\n".join(f'  "{k}": "{v}",' for k, v in sorted(routes.items()))
out = (
    "// GENERATED by scripts/gen-content-dates.py - do not edit by hand.\n"
    "// Last commit date per route, used for <lastmod> in the sitemap.\n"
    "export const CONTENT_DATES: Record<string, string> = {\n"
    + body + "\n};\n\n"
    "/** lastmod for a route, or undefined when unknown (better than a fake date). */\n"
    "export const lastMod = (route: string) =>\n"
    "  CONTENT_DATES[route] ? new Date(CONTENT_DATES[route]) : undefined;\n"
)
open("app/lib/contentDates.ts", "w", encoding="utf-8").write(out)
print(f"wrote app/lib/contentDates.ts with {len(routes)} routes")
